# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7d038b0e18426c54906a29e93d95be27a14b4fb08952413c82f4b254f87eb85ee4ee5dfdd47e67a26aa360f4b28b618902b39612d0c611acf96949148141bee

test:
  secret_key_base: a3b11a9bbc7420fdffaddd16927d78527ff1b4dcf0375152df751c6e9b9f1726c02c163c9a6a6fe32455eb156b5fcc10d0c1499320e270f63ae2f62759a29f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
